//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Context : DbContext
    {
        public Context()
            : base("name=AccountingSystemEntities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Corpus> Corpora { get; set; }
        public virtual DbSet<District> Districts { get; set; }
        public virtual DbSet<Education> Educations { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<LessonNumberInfo> LessonNumberInfoes { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<ScheduleRecord> ScheduleRecords { get; set; }
        public virtual DbSet<Spezialisation> Spezialisations { get; set; }
        public virtual DbSet<Street> Streets { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<StudentState> StudentStates { get; set; }
        public virtual DbSet<StudentStatu> StudentStatus { get; set; }
        public virtual DbSet<StudentStatusOnLesson> StudentStatusOnLessons { get; set; }
        public virtual DbSet<Subject> Subjects { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TeacherInfo> TeacherInfoes { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<CorpusView> CorpusViews { get; set; }
        public virtual DbSet<GroupView> GroupViews { get; set; }
        public virtual DbSet<ScheduleView> ScheduleViews { get; set; }
        public virtual DbSet<StudentStatusView> StudentStatusViews { get; set; }
        public virtual DbSet<StudentView> StudentViews { get; set; }
        public virtual DbSet<SubjectView> SubjectViews { get; set; }
        public virtual DbSet<TeacherView> TeacherViews { get; set; }
    }
}
