//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Group()
        {
            this.ScheduleRecords = new HashSet<ScheduleRecord>();
            this.Students = new HashSet<Student>();
        }
    
        public int GroupId { get; set; }
        public int CorpusId { get; set; }
        public string GroupName { get; set; }
        public string SpezialisationCode { get; set; }
        public System.DateTime DateEntrance { get; set; }
        public bool IsBudget { get; set; }
    
        public virtual Corpus Corpus { get; set; }
        public virtual Spezialisation Spezialisation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScheduleRecord> ScheduleRecords { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student> Students { get; set; }
    }
}
