//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduleRecord
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ScheduleRecord()
        {
            this.StudentStatusOnLessons = new HashSet<StudentStatusOnLesson>();
        }
    
        public int ScheduleRecordId { get; set; }
        public int TeacherId { get; set; }
        public int SubjectId { get; set; }
        public int GroupId { get; set; }
        public int DayOfWeek { get; set; }
        public int LessonNumber { get; set; }
        public Nullable<bool> IsDenominator { get; set; }
        public Nullable<int> HallNumber { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual LessonNumberInfo LessonNumberInfo { get; set; }
        public virtual Subject Subject { get; set; }
        public virtual TeacherInfo TeacherInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentStatusOnLesson> StudentStatusOnLessons { get; set; }
    }
}
