//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduleView
    {
        public string Группа { get; set; }
        public string Предмет { get; set; }
        public string Фио_преподователя { get; set; }
        public int День_недели { get; set; }
        public int Номер_пары { get; set; }
        public Nullable<bool> Знаменатель { get; set; }
        public System.TimeSpan Начало_пары { get; set; }
        public System.TimeSpan Конец_пары { get; set; }
        public Nullable<int> Номер_кабинета { get; set; }
        public Nullable<int> Кабинет_преподователя { get; set; }
        public int Id { get; set; }
    }
}
