//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentStatusView
    {
        public string Предмет { get; set; }
        public int День_недели { get; set; }
        public int Номер_пары { get; set; }
        public string Фио_преподователя { get; set; }
        public string Фио_студента { get; set; }
        public string Статус_студента { get; set; }
    }
}
