//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubjectView
    {
        public string Предмет { get; set; }
        public string Код_специализации { get; set; }
        public string Специализация { get; set; }
    }
}
