//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeacherInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TeacherInfo()
        {
            this.ScheduleRecords = new HashSet<ScheduleRecord>();
        }
    
        public int UserId { get; set; }
        public int CorpusId { get; set; }
        public Nullable<int> EducationId { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string Patronymic { get; set; }
        public string Spezialisation { get; set; }
        public string University { get; set; }
        public System.DateTime DateBirth { get; set; }
        public string Phone { get; set; }
        public Nullable<int> HallNumber { get; set; }
    
        public virtual Corpus Corpus { get; set; }
        public virtual Education Education { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScheduleRecord> ScheduleRecords { get; set; }
        public virtual User User { get; set; }
    }
}
