//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeacherView
    {
        public string Отделение { get; set; }
        public string Фио { get; set; }
        public string Образование { get; set; }
        public string Специальность { get; set; }
        public string Университет { get; set; }
        public System.DateTime Дата_рождения { get; set; }
        public string Служебный_телеон { get; set; }
        public string Логин { get; set; }
        public string Пароль { get; set; }
        public string Роль { get; set; }
        public Nullable<int> Кабинет { get; set; }
        public int Id { get; set; }
    }
}
